default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: db
  # host: localhost
  port: 5432

development:
  <<: *default
  database: trading_stocks_dev

test:
  <<: *default
  database: trading_stocks_test

production:
  <<: *default
  database: trading_stocks